- .github/PULL_REQUEST_TEMPLATE.md
> Create GitHub PR template

- backend/typescript/services/interfaces/authService.ts
- backend/typescript/services/interfaces/userService.ts
- backend/typescript/types.ts
Foundation of:
[Firebase authentication & user services using PostgreSQL (Sequelize)](https://www.notion.so/uwblueprintexecs/In-house-authentication-user-services-using-PostgreSQL-Sequelize-3338837f5b4c44b4a011ba60339f6403)
[Firebase authentication & user services using MongoDB (Mongoose)](https://www.notion.so/uwblueprintexecs/Firebase-authentication-user-services-using-MongoDB-Mongoose-1618340d0baa4549a8e38cd521c149c0)
* No implementation yet, just defining the desired functionalities of the user and auth services
1. N/A
* Completeness of proposed functionalities
> Create user and auth service interfaces in TypeScript backend

- hooks/post-merge
- secret.config
- setup.sh
- update_secret_files.py
[Setup Secret Manager](https://www.notion.so/uwblueprintexecs/Setup-Secret-Manager-a5b7c88ec2474349999e4b3a9ed767a3)
* Copied scripts from https://github.com/uwblueprint/vault-resources
* Followed instructions [here](https://www.notion.so/uwblueprintexecs/Secret-Management-2d5b59ef0987415e93ec951ce05bf03e)
1. Setup Vault client locally: follow instructions [here](https://www.notion.so/uwblueprintexecs/Secret-Management-2d5b59ef0987415e93ec951ce05bf03e)
2. Pull secrets (command in Slack channel)
* Does it work :)
> Setup secret manager

- backend/typescript/package.json
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/server.ts
- backend/typescript/services/interfaces/authService.ts
- backend/typescript/yarn.lock
[CRUD REST endpoints for User and auth (Express.js)](https://www.notion.so/uwblueprintexecs/CRUD-REST-endpoints-for-User-and-auth-Express-js-513c45ef195647bf91d3f119773c254b)
* Standard Express.js endpoints
* Auth endpoints set the refresh token in a cookie, following secure client-side token storage practices discussed previously
1. Create some users: send POST requests to `/users` with bodies in this format:
```
{
"firstName": "First",
"lastName": "Last",
"email": "first.last@domain.com",
"role": "Admin",
"password": "password123"
}
```
2. Retrieve users by sending GET requests to `/users`. Try adding `?userId=<insert-userid>` and `?email=<insert-email>` query parameters
3. Update a user: send a PUT request to `/users/<insert-userid>` with a body in this format:
```
{
"firstName": …
```
> Create TypeScript user and auth REST endpoints

- backend/typescript/graphql/index.ts
- backend/typescript/graphql/resolvers/authResolvers.ts
- backend/typescript/graphql/types/authType.ts
- backend/typescript/server.ts
[GraphQL auth resolvers](https://www.notion.so/uwblueprintexecs/GraphQL-auth-resolvers-082310793eb04e9598e82b81dd78dac7)
* Mirrored auth REST endpoints implementation in #9 
1. Run the application, then test using **Postman** (easier to view response headers than in the GraphQL playground). Simply send POST requests to `http://localhost:5000/graphql`, and set the body type to be GraphQL
2. Create a user if you don't have one, see instructions in #13 
3. Login by executing this mutation, check that you receive an access token and that a `Set-Cookie` header is returned with the refresh token.
```graphql
mutation {
login(email: "your.email@domain.org", password: "your-password")
}
```
4. Refresh token by executing this mutation, ensure that a `Cookie: refreshToken=<insert-refreshToken>` …
> Create GraphQL auth resolvers

- backend/typescript/graphql/index.ts
- backend/typescript/middlewares/auth.graphql.ts
- backend/typescript/middlewares/auth.ts
- backend/typescript/package.json
- backend/typescript/yarn.lock
[Integrate authentication service into GraphQL resolvers](https://www.notion.so/uwblueprintexecs/Integrate-authentication-service-into-GraphQL-resolvers-5a4c776a30414197b46fc529e80a4626)
* Created auth middleware, mirrors the REST version (main difference in function signature), applied to GraphQL schema via the [graphql-middleware](https://www.npmjs.com/package/graphql-middleware) package
1. Run the application and go to the GraphQL playground at http://localhost:5000/graphql
2. Create a user if you don't have one
3. Generate an access token, this checks that unauthenticated users are able to execute this mutation
```graphql
mutation {
login(email: "username@domain.org", password: "password")
}
```
4. Refresh token. Again, this checks that unauthenticated users are able to execute this …
> Create GraphQL auth middleware and secure resolvers

- .gitignore
- backend/typescript/package.json
- backend/typescript/services/implementations/emailService.ts
- backend/typescript/services/interfaces/emailService.ts
- backend/typescript/types.ts
- backend/typescript/yarn.lock
[Design EmailService interface](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d?p=d680308081414fc4a95bf2a01160e112)
* Add service for sending out generic emails
1. Navigate to the Google Cloud Platform console and click on the project/create a new project.
2. Navigate to "APIs & Services" on the left pane and click on Credentials.
3. Click "Create Credentials" with OAuth Client ID option, and fill in the form (set user type to internal)
4. Navigate back to the Credentials page and click Create Credentials again with OAuth Client ID option. Select "Web Application" and set "Authorised Redirect URIs" to https://developers.google.com/oauthplayground
5. Click Create and keep the Client ID and secret given.
6. Navigate to …
> Add TypeScript email service

- backend/python/app/services/implementations/email_service.py
- backend/python/app/services/interfaces/email_service.py
- backend/python/requirements.txt
[Design EmailService interface](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d?p=d680308081414fc4a95bf2a01160e112)
* Add email service for python
1. Follow the steps in https://github.com/uwblueprint/starter-code-v2/pull/18
2. Under the Google Cloud Platform dashboard, navigate to APIs & Services -> Library -> Gmail API, and click Enable.
3. Create a local config file that looks like the following and fill in the fields.
```
credentials = {
"refresh_token": "",
"token_uri": "https://oauth2.googleapis.com/token",
"client_id": "",
"client_secret": "",
}
```
4. Create a new EmailService and call send_email
* Any suggestions for organizing files or docstring formatting? There aren't any python services right now so I just mirrored the typescript structure
> Add python email service

- backend/python/app/__init__.py
- backend/python/app/rest/__init__.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/rest/user_routes.py
- docker-compose.yml
[CRUD REST endpoints for User and auth](https://www.notion.so/uwblueprintexecs/CRUD-REST-endpoints-for-User-1e011852254e45dd96f0cd5fbf10058a)
Mirrors #9 
1. Setup application, see [instructions](https://uwblueprint.slack.com/archives/C01JSU8JJCB/p1619487582007600). Make sure to comment out `ts-backend` in `docker-compose.yml`
2. Setup EmailService, see instructions in #19. Update lines 18 and 19 in `backend/python/app/rest/auth_routes.py` to your email and display name. Add the following values to your root `.env` file:
```
EMAIL_REFRESH_TOKEN=<insert-your-token>
EMAIL_CLIENT_SECRET=<insert-your-secret>
EMAIL_CLIENT_ID=<insert-your-id>
```
3. Run the application
4. Create some users, send POST requests to `/users` with bodies in this format:
```
{
"first_name": "First",
"last_name": …
```
> Create Flask user and auth REST endpoints

- backend/python/app/__init__.py
- backend/python/app/resources/token.py
- backend/python/app/rest/__init__.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/rest/user_routes.py
- backend/python/app/services/implementations/auth_service.py
- backend/python/app/services/interfaces/auth_service.py
- backend/python/app/utilities/firebase_rest_client.py
- docker-compose.yml
Addresses the authentication service part of [Firebase authentication & user services using MongoDB](https://www.notion.so/uwblueprintexecs/Firebase-authentication-user-services-using-MongoDB-526ab9c258c340e5a15e9e25da967982)
Mirrors #7
Wait for REST layer to be completed.
* backend/python/app/services/implementations/auth_service.py
* backend/python/app/utilities/firebase_rest_client.py
> Create Python AuthService

- backend/python/app/middlewares/auth.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/rest/entity_routes.py
- backend/python/app/rest/user_routes.py
- backend/python/app/services/implementations/auth_service.py
[User authentication middleware for REST endpoints](https://www.notion.so/uwblueprintexecs/User-authentication-middleware-for-REST-endpoints-307228b22d5742fb840ea114e06eb2ce)
* Mirrors #10 
* Created decorators using functools to implement middleware, referenced [this](https://stackoverflow.com/questions/14367991/flask-before-request-add-exception-for-specific-route) and [this](https://stackoverflow.com/questions/5929107/decorators-with-parameters)
Prereqs: follow #23 to setup
1. Assuming you have a user already, generate an access token: POST `/auth/login` with a body in this format:
```
{
"email": "first.last@domain.org",
"password": "password"
}
```
2. Send requests to `/entities` REST endpoints with `Authorization: bearer <insert-access-token>` header, you should get a normal response …
> Create auth middleware and integrate into REST endpoints in Python backend

- backend/python/app/rest/auth_routes.py
- backend/python/app/services/implementations/email_service.py
- backend/python/app/services/interfaces/email_service.py
[Ticket Name](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d)
* Update docstrings and add email service logging as referenced in https://github.com/uwblueprint/starter-code-v2/pull/20
1.
*
> Update docstrings and add email service logging

- backend/python/app/models/entity_mg.py
- backend/python/app/rest/entity_routes.py
- backend/python/app/services/implementations/entity_service.py
- backend/python/app/services/implementations/entity_service_mg.py
[Ticket Name](https://www.notion.so/uwblueprintexecs/Entity-CRUD-service-using-MongoDB-mongoengine-e395e9b785944baaacdeb46e0dcd36a1)
* Essentially building off of what was previously made in the pfrp starter code
1. docker-compose up --build the project, comment out ts-backend portion of the docker-compose.yml
2. Make a GET request to localhost:5000/entities, verify that the output is   ```[ ] ```
3. Make a POST request to localhost:5000/entities, with the JSON as 
```
{
"string_field": "Joe",
"int_field": 21,
"string_array_field": ["C"],
"enum_field": "B",
"bool_field": true
}
```
Verify that the output matches after making another GET request to localhost:5000/entities and contains an id
4. Make a GET request to localhost:5000/entities/id replacing id with the id of the newly created …
> Python mongo

- backend/python/app/__init__.py
- backend/python/requirements.txt
- backend/typescript/server.ts
N/A - quick fix
* Configured allowed origins and credentials in both the TypeScript and Python backends
1. Make a request from the frontend (running on localhost:3000)
* backend/python/app/__init__.py
* backend/typescript/server.ts
> Add CORS configurations in TypeScript and Python backends

- backend/python/app/resources/auth_dto.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/services/implementations/auth_service.py
- backend/python/app/services/interfaces/auth_service.py
- backend/typescript/graphql/resolvers/authResolvers.ts
- backend/typescript/graphql/types/authType.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/interfaces/authService.ts
- backend/typescript/types.ts
* [Return full user from login and refresh auth endpoints](https://www.notion.so/uwblueprintexecs/Return-full-user-from-login-and-refresh-auth-endpoints-a6b6688db62a439c883e21aa10654820)
* [Integrate EmailService into AuthService](https://www.notion.so/uwblueprintexecs/Integrate-EmailService-into-AuthService-7a52505a692245cb9bf205d0e834628c)
* Modified `auth/login` REST endpoints in both the TypeScript and Python backends to return full user info (name, email address, role, user_id) along with the access_token
* Modified TypeScript GraphQL login mutation to return full user info
* Integrated EmailService into TypeScript AuthService for sending password reset links
* Renamed Python `auth/reset_password` endpoint to `auth/resetPassword`
**Note**: you can test using either or both of the …
> Modify backend: return user from login, integrate EmailService into TS AuthService, rename reset_password endpoint

- backend/python/app/rest/entity_routes.py
N/A - bug fix
* Added "Admin" as an authorized role for entities endpoints
1. Try any of the Python entities endpoints with an "Admin" user
N/A
> Fix role based authorization on Python entities endpoints

- backend/typescript/server.ts
- frontend/package.json
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Logout.tsx
- frontend/src/components/auth/RefreshCredentials.tsx
- frontend/src/components/auth/ResetPassword.tsx
- frontend/src/components/crud/CreateForm.tsx
- frontend/src/components/crud/DisplayTableContainer.tsx
- frontend/src/components/crud/UpdateForm.tsx
- frontend/src/index.tsx
- frontend/yarn.lock
* [GraphQL client for Entity endpoints](https://www.notion.so/uwblueprintexecs/GraphQL-client-for-Entity-endpoints-e01b7045f2d14743b20ec4dccd4dd991)
* [GraphQL client: login & logout components](https://www.notion.so/uwblueprintexecs/GraphQL-client-login-logout-components-cc5e2dd642254a1d923a2804155ecaac)
* Integrated Apollo Client
* Use `useQuery` and `useMutation` hooks to call into GraphQL API
* Configured CORS options in Apollo Server
1. Run the application (choose TypeScript backend)
2. Try all of functionalities on the frontend
* Login
* Refresh Credentials
* Reset Password
* Create Entity
* Update Entity
* Display Entities
* Logout
* frontend/src/components/auth/Login.tsx (Mutation)
* frontend/src/components/crud/DisplayTableContainer.tsx (Query)
* All the other components run …
> Create GraphQL auth and entities clients

- backend/python/app/models/__init__.py
- backend/python/app/models/user_pg.py
- backend/python/app/services/implementations/user_service_pg.py
[Firebase authentication & user services using PostgreSQL (SQLAlchemy)](https://www.notion.so/uwblueprintexecs/Firebase-authentication-user-services-using-PostgreSQL-SQLAlchemy-1176e74893f742a78ed57302067af05c)
* Created SQLAlchemy PostgreSQL model for users
* Created SQLAlchemy PostgresSQL UserService 
1. Replace user_service_mg with user_service_pg in backend/python/app/rest/user_routes.py
2. Note that the model init was changed so that tables are not automatically dropped and recreated. In order to restore that, change erase_db_and_sync in backend/python/app/models/__init__.py to true.
3. To test, the same steps in [#23 ] can be used
* The update and delete functions could not be made atomic, as the SQLAlchemy `returning` function could not be called by the result of the query update …
> Create Python Postgres UserService

- frontend/src/components/crud/UpdateForm.tsx
No ticket, just a small fix
- Replaced "create" strings on the update form with "update"
- Replaced the default id string with a more realistic id value
1. Verify changes at `/entity/update`
*
> Change create to update on updateform page

- backend/python/app/models/__init__.py
N/A
* Changing the initial flag to true so that tables will be created on the initial run
1. Run the Python backend after removing the DB volume (`docker-compose down --volumes`), you should see tables being recreated.
* N/A
> Change erase_db_and_sync flag to True in Python backend

- backend/typescript/migrate.js
- backend/typescript/migrations/2021.05.30T04.43.57.create-table-example.ts
- backend/typescript/migrations/2021.05.30T04.47.28.add-column-example.ts
- backend/typescript/package.json
- backend/typescript/umzug.ts
- backend/typescript/yarn.lock
[Configure Sequelize Migrations](https://www.notion.so/uwblueprintexecs/Configure-Sequelize-Migrations-4b3aa00efd5c4b27a4345de228208a57)
* Installed the [Umzug](https://github.com/sequelize/umzug) migration tool (it contains the core migration logic used by the Sequelize CLI, we can't use Sequelize CLI directly as it does not yet support TypeScript migration files). Fun fact, Umzug means "move" in German!
* Followed [example](https://github.com/sequelize/umzug/tree/master/examples/1.sequelize-typescript) in the Umzug repo to set up the migration framework, added some example migrations for testing and demo
* Added documentation here: https://uwblueprint.github.io/starter-code-v2/docs/migrations/typescript-migrations.html
1. Run both the TypeScript backend and database containers (can …
> Configure Sequelize migrations

- backend/python/app/middlewares/user.py
- backend/python/app/middlewares/validate.py
- backend/python/app/resources/create_user_dto.py
- backend/python/app/resources/entity_dto.py
- backend/python/app/resources/update_user_dto.py
- backend/python/app/rest/entity_routes.py
- backend/python/app/rest/user_routes.py
[Python REST API input validation](https://www.notion.so/uwblueprintexecs/Python-REST-API-input-validation-d372faf0eaa0469cade8e6588f0d4299)
* Created middleware to ensure validation when using DTO endpoints for the Python backend
1. Send an invalid DTO shape or invalid type
2. Notice that it returns status 400 with a string that explains the error
* The decorator since this is my first time writing a decorator
> Add Python REST Validators

- README.md
- secret.config
N/A
* Added content catered towards users (first half, above divider) and devs (second half)
* Added nodemailer config path to secret.config (also pushed the file to Vault)
1. Try using the "rich diff" option to view the changes, or check the [rendered page](https://github.com/uwblueprint/starter-code-v2/blob/sherry/update-readme/README.md)
* Anything else that might be helpful to add?
> Update README.md and add nodemailer config path to secret.config

- backend/typescript/server.ts
- backend/typescript/services/implementations/storageService.ts
- backend/typescript/services/interfaces/storageService.ts
[Create TS FileStorageService](https://www.notion.so/uwblueprintexecs/Create-TS-FileStorageService-dd9b609e2f36403cb2ebab7688c38e35)
* Created file storage service for files with create, update, get, and delete function
* Create endpoint only creates if the file name does not already exist, otherwise throws an error
1. Go to the Firebase console for the project and go to `Storage`
2. Add the file you want to test with to `/backend/typescript`
3. Add `import FileStorageService from "./services/implementations/storageService";` and after `firebaseAdmin.initializeApp()...` add `const file: FileStorageService = new FileStorageService();` to `server.ts`
4. Add the following lines after `const file: FileStorageService = new FileStorageService();` and fill it in with the correct names:
```
// …
```
> Create TypeScript FileStorageService

- backend/python/app/__init__.py
- backend/python/app/config.py
- backend/python/requirements.txt
- backend/python/setup.py
- backend/python/tests/functional/conftest.py
- backend/python/tests/functional/test_user_routes.py
- backend/python/tests/functional/test_user_service.py
- backend/python/tests/unit/test_models.py
- backend/typescript/.eslintrc.js
- backend/typescript/Dockerfile
- backend/typescript/jest.config.ts
- backend/typescript/models/index.ts
- backend/typescript/package.json
- backend/typescript/services/implementations/__tests__/userService.test.ts
- backend/typescript/testUtils/setup.ts
- backend/typescript/testUtils/testDb.ts
- docker-compose.yml
- frontend/package.json
- frontend/src/App.test.tsx
- frontend/src/components/common/__tests__/MainPageButton.spec.tsx
- frontend/src/components/common/__tests__/__snapshots__/MainPageButton.spec.tsx.snap
- frontend/src/components/pages/__tests__/Default.test.tsx
- frontend/src/utils/__tests__/LocalStorageUtils.test.ts
- frontend/yarn.lock
[Add testing frameworks (pytest & jest)](https://www.notion.so/uwblueprintexecs/Task-Board-db95cd7b93f245f78ee85e3a8a6a316d?p=ee0e6bfa01b447e2888232d6d709e7d6)
* Provide some sample testing for python backend, typescript backend, and react frontend
1. Update secrets `vault kv get -format=json kv/internal-tools | python update_secret_files.py`
2. Run frontend tests: run `yarn test` in docker frontend container
2. Run ts-backend tests: run `yarn test` in docker backend ts container
3. Run python-backend tests: run `pip install -e .` followed by `pytest` in docker backend python container
e.g. 
```
docker ps # get container ID
docker exec <container id> yarn test
```
* python tests - test_models, test_user_routes
* ts backend tests - userService.test.ts
* frontend tests - Default.test.tsx, …
> Add testing frameworks

- backend/typescript/graphql/resolvers/entityResolvers.ts
- backend/typescript/graphql/types/entityType.ts
- backend/typescript/middlewares/validators/entityValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/models/entity.mgmodel.ts
- backend/typescript/models/entity.pgmodel.ts
- backend/typescript/package.json
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/services/implementations/EntityServiceMg.ts
- backend/typescript/services/implementations/EntityServicePg.ts
- backend/typescript/services/implementations/fileStorageService.ts
- backend/typescript/services/interfaces/IEntityService.ts
- backend/typescript/yarn.lock
Closes #80 
* Updated models to have a file name field
* Updated entity request DTO to have a filePath field and response DTO to have a fileName field
* Updated EntityService for Postgres and mongo to call FileStorageService methods
* Updated entity routes , added separate get endpoint for retrieving file by fileUUID
* Added file type validation
* Updated create/update entity GraphQL mutations to take a FileUpload type parameter (documentation https://www.apollographql.com/docs/apollo-server/data/file-uploads/)
* Added separate GraphQL query to retrieve file by fileUUID
* Refactor FileStorageService (changing the bucket field to bucketName field to prevent firebase functions from being called before initializeApp())
REST:
(using Postman)
1. Set the body to form-data and add the body field …
> Integrate TS FileStorageService into EntityService

- frontend/src/App.tsx
- frontend/src/components/auth/PrivateRoute.tsx
- frontend/src/components/common/MainPageButton.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/constants/Routes.ts
N/A
* Small refactor to turn path strings into constants
1. Run app, ensure pages load on route matches
* Routes.ts
* App.tsx
* Default.tsx
> Refactor route strings into constants

- backend/python/app/__init__.py
- backend/python/app/config.py
- backend/python/app/rest/entity_routes.py
- backend/python/app/rest/user_routes.py
- backend/python/app/utilities/csv_utils.py
- backend/python/tests/functional/test_user_routes.py
- backend/python/tests/functional/test_user_service.py
- backend/python/tests/unit/test_csv.py
- backend/python/tests/unit/test_models.py
Create backend utility to generate csv from tabular data, add option to return csv from bulk GET endpoints
[Ticket Name](https://www.notion.so/uwblueprintexecs/Create-backend-utility-to-generate-csv-from-tabular-data-add-option-to-return-csv-from-bulk-GET-end-19dd604265034b5b8cfe45a9f1aea84d)
*  CSV generation for Python with unwind and flattening functionality. Pytests tests have been written as well.
1. REST (using Postman)
Set the content-type in the headers to text/csv and the request type to GET on entities and users.
*  Unsure if the csv string is the exact output we want
*  CSV formatting functionality in generate_csv.py
> Backend CSV generation Python

- backend/typescript/graphql/resolvers/authResolvers.ts
- backend/typescript/graphql/resolvers/userResolvers.ts
- backend/typescript/graphql/types/authType.ts
- backend/typescript/middlewares/validators/authValidators.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/interfaces/authService.ts
- backend/typescript/types.ts
Closes #92 
* sendEmailVerificationLink function added to auth service instead, to make it more consistent with the reset password function, and so we don’t need the user service to have its own email service instance
* Downside is that in userRoutes, we have to instantiate an authService
* Note: existing admin users may have to send themselves a verification email link so that they can access endpoints once this is merged
* I did this just by adding `await authService.sendEmailVerificationLink("your email");` to the login endpoint and querying once
1. Start the server and navigate to http://localhost:5000/graphql . Use this mutation to register a user and verify that the user is created successfully in MongoDB atlas/postgres and in firebase console. Also verify that you are sent a …
> Create Typescript registration flow with email verification

- backend/python/app/middlewares/validate.py
- backend/python/app/resources/register_user_dto.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/rest/user_routes.py
- backend/python/app/services/implementations/auth_service.py
- backend/python/app/services/interfaces/auth_service.py
Closes #93 
* `sendEmailVerificationLink` function added to the auth service
* similar to #104 
* created a `RegisterUserDTO` in resources to validate requests
1. Post the following JSON body to localhost:5000/auth/register, and verify that the user is created in MongoDB atlas/postgres and in firebase console. Also verify that you receive an email verification link.
```
{
"first_name": "Test",
"last_name": "User",
"email": "insertemail",
"password": "insertpassword"
}
```
2. Try sending a GET request to localhost:5000/entities , using the returned access token. Verify that it fails.
3. Verify your email by clicking the link.
4. Try sending a GET request to localhost:5000/entities with the same token and verify that it fails.
5. Login and use the new token to get entities, and verify that …
> Create Python registration flow with email verification

- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/App.tsx
- frontend/src/components/auth/Login.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/constants/Routes.ts
Closes #94 
* Add sign-up button on login page redirecting to a sign-up page
* Add sign-up page with first name, last name, email, and password inputs
* Add REST and GraphQL `register` functions in `AuthAPIClient.ts`
1. Click on the sign-up button on the login page and verify that it redirects to the sign-up page
2. Fill in the form with an existing user's email and verify that the sign-up fails
3. Fill in the form with a user with an email that hasn't been used before and verify that it succeeds. Check that you are redirected to the main page. Check that your user is registered in the starter code firebase console. Check that your user is registered in the Mongo or Postgres `users` table.
* When a user registers but logs out before verifying their account, an error occurs. Are any …
> Frontend User Sign-Up

- backend/typescript/rest/authRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/services/implementations/userServicepg.ts
- backend/typescript/services/interfaces/authService.ts
- backend/typescript/services/interfaces/userService.ts
- backend/typescript/types.ts
- backend/typescript/utilities/firebaseRestClient.ts
Closes #102 
* Mirrors #112
1. Same as Python PR
*
> Integrate Google OAuth into TS

- backend/python/app/middlewares/validate.py
- backend/python/app/resources/register_user_dto.py
- backend/python/app/rest/auth_routes.py
- backend/python/app/rest/user_routes.py
- backend/python/app/services/implementations/auth_service.py
- backend/python/app/services/interfaces/auth_service.py
- backend/typescript/graphql/resolvers/authResolvers.ts
- backend/typescript/graphql/resolvers/userResolvers.ts
- backend/typescript/graphql/types/authType.ts
- backend/typescript/middlewares/validators/authValidators.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/interfaces/authService.ts
- backend/typescript/types.ts
- frontend/src/APIClients/AuthAPIClient.ts
- frontend/src/APIClients/BaseAPIClient.ts
- frontend/src/APIClients/EntityAPIClient.ts
- frontend/src/App.tsx
- frontend/src/components/auth/Signup.tsx
- frontend/src/constants/Routes.ts
N/A
* Followed [release instructions](https://github.com/uwblueprint/starter-code-v2#creating-a-release)
* Includes 3 commits from `main`: 7f803436b8fd2db1c12c56c12f95822b6156b128, 45b76fb13962688ba6568e141b46a50a7bbf2621, de7811552f7798eaf68cfc8f427ddbf5d0c2aa3a
* Fully integrates user registration (sign up) into the release branch
1. Checkout https://github.com/uwblueprint/starter-code-cli/pull/27
2. For the below stack combinations: generate starter-code using the CLI
**Stacks:** (changes are confined to the controller layer and frontend)
* TypeScript, REST, MongoDB, auth, no-file-storage
* TypeScript, GraphQL, MongoDB, auth, no-file-storage
* Python, REST, MongoDB, auth, no-file-storage
**General testing workflow:**
```bash
yarn dev --testing
git reset --hard …
```
> Create release v1.6.0

- backend/python/app/services/implementations/auth_service.py
N/A
* Small syntax fix
1. Run the Python backend and follow steps 3-9 in https://github.com/uwblueprint/starter-code-v2/pull/120
* N/A
> Fix email_verified syntax in Python auth_service

- frontend/.eslintrc.js
- frontend/src/App.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/components/pages/HooksDemo/EmojiSection.tsx
- frontend/src/components/pages/HooksDemo/HooksDemo.tsx
- frontend/src/components/pages/HooksDemo/emojis.ts
- frontend/src/components/pages/HooksDemo/index.ts
- frontend/src/components/pages/HooksDemo/styles.css
- frontend/src/constants/Routes.ts
Create and document use cases for the following
hooks on HooksDemo page:
* useState
* useRef
* useCallback
* useEffect
This page also includes uses and documentation for:
* React.memo
* React.forwardRef
https://github.com/uwblueprint/starter-code-v2/issues/97
https://github.com/uwblueprint/starter-code-v2/issues/98
https://github.com/uwblueprint/starter-code-v2/issues/99
https://github.com/uwblueprint/starter-code-v2/issues/101
* Create components demo-ing React's common hooks
* Document hooks in components for easy dev ramp-up
1. Visit Hooks Demo page `/hooks`
* HooksDemo.tsx
* EmojiSection.tsx
> Create HooksDemo page

- frontend/.eslintrc.js
- frontend/src/App.tsx
- frontend/src/components/pages/Default.tsx
- frontend/src/components/pages/HooksDemo/EmojiSection.tsx
- frontend/src/components/pages/HooksDemo/HooksDemo.tsx
- frontend/src/components/pages/HooksDemo/emojis.ts
- frontend/src/components/pages/HooksDemo/index.ts
- frontend/src/components/pages/HooksDemo/styles.css
- frontend/src/constants/Routes.ts
N/A
* Followed [release instructions](https://github.com/uwblueprint/starter-code-v2#creating-a-release)
* Adds only a single commit from `main`: e7730e4bdcb1a7ea91219af2666c05ec8eb4beeb (React hooks demo)
**Stack combinations:**
* TypeScript, REST, MongoDB, auth, no-file-storage
* TypeScript, REST, MongoDB, no-auth, no-file-storage
**General testing workflow:**
```bash
yarn dev --testing
git reset --hard HEAD
```
1. Go to the hooks demo page and verify all functionalities
* Check all changes introduced in #125 are included
> Create release v1.9.0

- backend/python/app/static/openapi.json
- backend/typescript/swagger.yml
N/A
* Updated `backend/typescript/swagger.yml` and `backend/python/app/static/openapi.json` with:
* multipart/formdata request bodies for POST and PUT `/entities` endpoints
* `fileName` field in entity responses
* `/entities/files/{:fileUUID}` endpoint
* `/auth/register` endpoint
* OAuth sign-in request body type for `/auth/login`
1. Run the application with TypeScript and Python backends separately, go to `http://localhost:5000/api-docs` and test UI for the modified endpoints
2. Make sure to select `multipart/formdata` from the dropdown when applicable
* Any missing documentation?
> Update Swagger API docs

- backend/python/app/__init__.py
- backend/python/app/static/openapi.json
- backend/typescript/server.ts
- backend/typescript/swagger.yml
- frontend/src/components/crud/UpdateForm.tsx
N/A
* Followed [release instructions](https://github.com/uwblueprint/starter-code-v2#creating-a-release)
* Includes 1 commit from `main`: f2dfd77ccebfaa2df816ed54140fd694e5c0e03f (Swagger API doc updates)
* Adds Firebase initialization when file storage is used without auth (edge case that we previously missed)
1. Generate starter code for the following stack combinations
* TypeScript, REST, PostgreSQL, auth, file-storage
* TypeScript, REST, PostgreSQL, no-auth, file-storage
* TypeScript, REST, PostgreSQL, auth, no-file-storage
* TypeScript, REST, PostgreSQL, no-auth, no-file-storage
* Python, REST, PostgreSQL, auth, file-storage
* Python, REST, PostgreSQL, no-auth, file-storage
* Python, REST, PostgreSQL, auth, no-file-storage
* Python, REST, PostgreSQL, no-auth, no-file-storage
2. Run …
> Create release v1.9.2

- backend/typescript/services/implementations/EntityServicePg.ts
- backend/typescript/services/implementations/userServicepg.ts
N/A
Cast type of `id` to string in responses from the PostgreSQL user and entity services (the `id` is typed as `string` in the user and entity DTOs but we somehow got past typechecking before and returned numbers).
1. Modify `backend/typescript/rest/userRoutes.ts`, `backend/typescript/rest/authRoutes.ts`, and `backend/typescript/middlewares/auth.ts` to import the PostgreSQL version of `UserService`
2. Comment out the `py-backend` service in `docker-compose.yml`
3. Run the application
```bash
```
4. Test all `/users` and `/entities` endpoints and verify that the `id`s in responses are strings
Instead of this approach of always converting the `id` to string, should we define separate DTOs for PostgreSQL services where the `id` is number? My justification for …
> Return string id from TypeScript PostgreSQL user and entity services

- .github/workflows/lint.yml
- backend/typescript/graphql/resolvers/authResolvers.ts
- backend/typescript/graphql/resolvers/entityResolvers.ts
- backend/typescript/graphql/resolvers/userResolvers.ts
- backend/typescript/middlewares/auth.graphql.ts
- backend/typescript/middlewares/auth.ts
- backend/typescript/middlewares/validators/authValidators.ts
- backend/typescript/middlewares/validators/entityValidators.ts
- backend/typescript/middlewares/validators/userValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/migrate.js
- backend/typescript/models/index.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/services/implementations/userServicepg.ts
- backend/typescript/testUtils/testDb.ts
- backend/typescript/umzug.ts
- backend/typescript/utilities/firebaseRestClient.ts
- backend/typescript/utilities/logger.ts
- frontend/src/components/crud/DisplayTableContainer.tsx
- frontend/src/index.tsx
Closes #141 
* Added GitHub Actions workflow file for running linters
* Fixed existing lint and formatting errors
Do a simple smoke test; there shouldn't be any errors introduced as the changes only consist of additions of type annotations and `eslint-disable` comments.
1. Comment out `py-backend` in `docker-compose.yml`
2. Run the application
```bash
```
3. Test all auth and entity CRUD features from the frontend and ensure they work as expected
4. Check the workflow logs of this PR, verify that the lint run passed (there are 2 warnings from the TypeScript backend lint, but they won't come up in the the scrubbed versions of those files)
* N/A
> Create GitHub Actions linting workflow and fix lint errors

- backend/typescript/middlewares/validators/entityValidators.ts
- backend/typescript/models/index.ts
- backend/typescript/rest/authRoutes.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/rest/userRoutes.ts
- backend/typescript/services/implementations/EntityServiceMg.ts
- backend/typescript/services/implementations/EntityServicePg.ts
- backend/typescript/services/implementations/authService.ts
- backend/typescript/services/implementations/emailService.ts
- backend/typescript/services/implementations/fileStorageService.ts
- backend/typescript/services/implementations/userService.ts
- backend/typescript/services/implementations/userServicepg.ts
- backend/typescript/utilities/errorUtils.ts
N/A - fixing an [issue](https://uwblueprint.slack.com/archives/C021C0R7KM2/p1636514814001600) raised in the #internal-tools-help channel
Typed all catch clause errors as `unknown` and created utility function to retrieve error message
1. Run the TypeScript backend (comment out `py-backend` and `frontend`), ensure it compiles successfully
```
```
2. Trigger an error (e.g. login with wrong password) and verify that error message is correctly returned
* N/A
> Fix error message typing in backend/typescript

- backend/typescript/jest.config.ts
N/A
* Followed release instructions
* Includes 1 commit from main: a21b66b4feec496aa75cdd952f78951175b360a3
Generate each of the following combinations using the CLI with the `--testing` flag:
**Language**|**API**|**DB**|**Auth**|**File Storage**|**Done**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
TypeScript|REST|PostgreSQL|Yes|Yes| ✔️
TypeScript|REST|PostgreSQL|Yes|No| ✔️
TypeScript|REST|PostgreSQL|No|Yes| ✔️
TypeScript|REST|PostgreSQL|No|No| ✔️
TypeScript|REST|MongoDB|Yes|Yes| ✔️
TypeScript|REST|MongoDB|Yes|No| ✔️
TypeScript|REST|MongoDB|No|Yes| ✔️
TypeScript|REST|MongoDB|No|No| ✔️
TypeScript|GraphQL|PostgreSQL|Yes|Yes| ✔️
TypeScript|GraphQL|PostgreSQL|Yes|No| ✔️
TypeScript|GraphQL|PostgreSQL|No|Yes| ✔️
TypeScript|GraphQL|PostgreSQL|No|No| ✔️
TypeScript|GraphQL|MongoDB|Yes|Yes| ✔️ …
> Create release v1.11.3

- README.md
N/A
* Update set up instructions
View changes with "rich diff" settings, check spelling and formatting
* Any missing steps?
> Update set up instructions in README

- frontend/src/components/crud/CreateForm.tsx
- frontend/src/components/crud/UpdateForm.tsx
* Small fix for removing double comment for the scrubber, should not impact the release branch
*
> Fix double comment  for scrubber

- backend/typescript/graphql/index.ts
- backend/typescript/graphql/resolvers/entityResolvers.ts
- backend/typescript/graphql/types/entityType.ts
- backend/typescript/middlewares/validators/entityValidators.ts
- backend/typescript/middlewares/validators/util.ts
- backend/typescript/migrations/2022.01.10T17.43.07.create-entity-table.ts
- backend/typescript/models/entity.model.ts
- backend/typescript/rest/entityRoutes.ts
- backend/typescript/server.ts
- backend/typescript/services/implementations/entityService.ts
- backend/typescript/services/interfaces/IEntityService.ts
- backend/typescript/swagger.yml
No Notion ticket, see **SCV2 Maintainability Exploration** document, section March 19, item 3
* Remove all `auth` and `file-storage` tags in typescript backend
* Remove all code under `no-auth` and `no-file-storage` tags in typescript backend
1. Run e2e tests for 4 stack combinations {REST, GraphQL} x {PostgreSQL, MongoDB}
* Are there any files where tags still need to be removed? 
* Are there any files where tags should not have been removed from?
> Remove tags from typescript backend

- setup_secrets.sh
- vault_setup.sh
[Write a script that automates fetching of secrets from vault and populates an env file with it](https://www.notion.so/uwblueprintexecs/Task-Board-929f5a7288854adebb007cbd77be88a3?p=134a74bdcbc841329d5ad2c7c612bf4a&pm=s)
* Write a bash script to fetch secrets from vault secret and store them in .env file
1. set up vault secret and store several secrets
2. ./vault_setup.sh or ./vault_setup.sh --output_path <OUTPUT_FILE_PATH>
*
> Write a script that automates fetching of secrets from vault and populates an env file with it

- push_secrets.sh
[Create a Way for Existing Projects to Migrate to Vault Secrets](https://www.notion.so/uwblueprintexecs/Create-a-Way-for-Existing-Projects-to-Migrate-to-Vault-Secrets-a4c0239d7217466cb0016d946b06283f?pvs=4)
* reads env file (provided by path), adds each key, value pair to vault secrets
* skips secrets with existing key to avoid overwriting existing secrets
1. Ensure you have a vault secrets account and are logged in: ```vlt login```
2. Run script using ```./push_secrets.sh ./path/to/env/file [organization name (optional)] [project name (optional)]```
3. Check vault secrets web page to see if secrets have been properly added
Note that using CLI to add secrets will change all keys to lowercase value as key objects are case insensitive.
*
> Add script to push existing env secrets to vault secrets

- backend/typescript/Dockerfile
[[Bug] Libcurl issues with Docker](https://www.notion.so/uwblueprintexecs/Bug-Libcurl-issues-with-Docker-4ca04ac029ca4fb3aa1e488defbbdf3e?pvs=4)
Was getting error
```
[4/6] RUN apt-get update && apt-get install -y libcurl3:
#8 0.511 Ign:1 http://deb.debian.org/debian stretch InRelease
#8 0.531 Ign:2 http://deb.debian.org/debian stretch-updates InRelease
#8 0.567 Ign:3 http://deb.debian.org/debian stretch Release
#8 0.589 Ign:4 http://deb.debian.org/debian stretch-updates Release
#8 0.604 Ign:5 http://security.debian.org/debian-security stretch/updates InRelease
#8 0.605 Ign:6 http://deb.debian.org/debian stretch/main all Packages
#8 0.617 Ign:7 http://security.debian.org/debian-security stretch/updates Release
#8 0.621 Ign:8 http://deb.debian.org/debian stretch/main arm64 Packages
#8 …
```
> Fixed docker unable to install libcurl
